name: portfolio
services:
  db:
    # # psql -U postgres -p 5431
    image: postgres:12.1-alpine
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: mypgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data:Z
