version: '3'

services:
  strapi:
    build:
      context: .
      args: 
        - tunnel_id=e813e6cf-4051-448b-a837-6216ccd103d2
        - backend_url=strapi.cant-overlook-this.uk
    # command: npx live-server .
    volumes:
      - ./.tmp.production:/usr/src/app/.tmp
    env_file:
      - .env.prod