version: "3"
services:
  strapi:
    image: strapi/strapi
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ./app:/usr/src/api/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
