schema:
  - ./src/graphql/schemas/strapi.graphql
  - ./src/graphql/fragments/app.graphql
documents:
  - ./src/graphql/queries/**/*.graphql
extensions:
  codegen:
    generates:
      ./dist/graphql/query.tsx:
        plugins:
          - add:
              content: '// @ts-nocheck'
          - add:
              content: 'import { ComponentFrontendComponentsSelectedProjectDetails, Exact } from "./schema"'
          - typescript-operations
      ./dist/graphql/schema.tsx:
        plugins:
          - typescript