version: '3.8'
services:
  app:
    build:
      context: ../../
      dockerfile: ./apps/strapi/Dockerfile
    networks:
      - default
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DATABASE_CLIENT=postgres
    ports:
      - '8080:1337'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - default

networks:
  default:
    driver: bridge