version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      # should contain POSTGRES_USER and POSTGRES_PASSWORD and POSTGRES_DB
      - .env
    ports:
      - '5432:5432'

