version: '3.8'
services:
  db:
    image: postgres #:15-alpine #:14.1-alpine
    restart: always
    env_file:
      # should contain POSTGRES_USER and POSTGRES_PASSWORD and POSTGRES_DB
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
