name: deploy-do
run-name: deploy-do

on:
  push:

jobs:
  deploy:
    name: install docts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: upload app-spec to digitalOcean
        run: doctl app update $PROJECT_ID --spec app-spec.yaml
        env:
          PROJECT_ID: ${{ secrets.DIGITALOCEAN_PROJECT_ID }}
