name: Build, Test and Deploy to Prod

on:
  push:

env:
  SQLX_OFFLINE: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          key: ${{ secrets.DROPLET_KEY }}
          username: root
          script: |
            cd ~/app
            git pull

            export APP_KEYS=${{ secrets.STRAPI_APP_KEYS }} 
            export API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }}   
            export ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}   
            export TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}  
            export JWT_SECRET=${{ secrets.STRAPI_JWT_SECRET }}   

            docker-compose down
            docker-compose build
            docker-compose up -d
